import mcpi.minecraft as minecraft
import mcpi.block as block

mc = minecraft.Minecraft.create()

pos = mc.player.getTilePos()

# Set out the dice dots
mc.setBlock(pos.x + 3, pos.y, pos.z, block.STONE.id)
mc.setBlock(pos.x + 3, pos.y + 2, pos.z, block.STONE.id)
mc.setBlock(pos.x + 3, pos.y + 4, pos.z, block.STONE.id)
mc.setBlock(pos.x + 3, pos.y, pos.z + 4, block.STONE.id)
mc.setBlock(pos.x + 3, pos.y + 2, pos.z + 4, block.STONE.id)
mc.setBlock(pos.x + 3, pos.y + 4, pos.z + 4, block.STONE.id)

#  Fill the dice
mc.setBlock(pos.x + 3, pos.y, pos.z - 1, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y, pos.z + 1, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y, pos.z + 2, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y, pos.z + 3, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 1, pos.z - 1, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 1, pos.z, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 1, pos.z + 1, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 1, pos.z + 2, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 1, pos.z + 3, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 1, pos.z + 4, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 1, pos.z + 5, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 2, pos.z - 1, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 2, pos.z + 1, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 2, pos.z + 2, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 2, pos.z + 3, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 2, pos.z + 5, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 3, pos.z - 1, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 3, pos.z, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 3, pos.z + 1, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 3, pos.z + 2, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 3, pos.z + 3, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 3, pos.z + 4, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 3, pos.z + 5, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 4, pos.z - 1, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 4, pos.z + 1, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 4, pos.z + 2, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 4, pos.z + 3, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 4, pos.z + 5, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 5, pos.z - 1, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 5, pos.z, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 5, pos.z + 1, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 5, pos.z + 1, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 5, pos.z + 2, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 5, pos.z + 3, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 5, pos.z + 4, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y + 5, pos.z + 5, block.WOOL.id)
mc.setBlock(pos.x + 3, pos.y, pos.z + 5, block.WOOL.id)
